[overlay]
width = 400
height = 200
font = "Arial"
font_size = 100
# red, green, blue values between 0 and 255
font_rgb = [255, 255, 255]
# red, green, blue values between 0 and 255
background_rgb = [255, 0, 0]
# how long to show data (seconds)
show_duration = 10

[watcher]
# how often to check system processes for likely games (seconds)
poll_frequency = 5
# how often to notify the overlay to show data (seconds)
notification_frequency = 300
# executable names to ignore; case-sensitive, supports regular expressions (wrap with 3 single quotes)
ignore = [
    "explorer.exe",
    "TrainerRoad.exe",
    '''^Zwiift.+''',
]
